### ISSUE TITLE
Clearer docs for Animated Elm-UI

### ISSUE THREAD

**Issue by andrewMacmurray** [andrewMacmurray/elm-simple-animation#12]
A few people have struggled to setup an `elm-ui` example when starting out with the library, this could be a sign that the docs aren't clear enough.

Some ideas:

+ Add a link to a full working Ellie 
+ Include an example that can be copy pasted into a project

Any other ideas, thoughts are welcome!

**Comment by 13r0ck** [comment]
Hi Andrew!
MY bad for not getting to the PR as soon as I promised on slack. Honestly this project is fantastic! The only issue I was having is that I am so new to Elm that basic stuff if hard for me :)

I'm not sure about the project in totality, but I am working in the PR with those changes above for the Elm-UI hook right now.

**Comment by 13r0ck** [comment]
Also not sure if you would like to expand the list of example animations, because if so I would love to contribute those too!
Like this slider? https://ellie-app.com/cRq3MtFgtfZa1

Idk, just having ha ton of fun haha XD

**Comment by andrewMacmurray** [comment]
No worries at all, thanks for making those changes!

I love the idea about expanding the examples, and having them in Ellie makes them a lot more portable. Go wild with more of them if you like 😄

And great to hear you're enjoying using it!
