### ISSUE TITLE
Creating an Empty animation

### ISSUE THREAD

**Issue by 13r0ck** [andrewMacmurray/elm-simple-animation#15]
This is created as a discussion for PR #14 .
I thought that adding Animation.empty would make it easier to match either no animation or some animation depending on the model.

My thinking is
```elm
animatedEl
    ( if shouldAnimate then
          expandFade
      else
          Animation.empty
    )
```
@andrewMacmurray mentioned that he usually makes conditional animations like:
```elm
if shouldAnimate then
   Animated.div expandFade [] [ element ]
else
   element
```
(For understanding both use the [expandFade](https://github.com/andrewMacmurray/elm-simple-animation) animation from the docs.)

In my opinion both work just fine (Andrew's might be slightly more performant, but I haven't tested it, but I can't imagine it is but much ). I just like the flexibility of being able to drop in an empty animation because both "Do I want this element to animate or not" and "Do I want an animated element or not" now have direct answers.

I'm interested what others think?
Thanks!

Also I am curious, should the name be `Animation.empty` because that is what the code is doing, or should it be `Animation.none` because that is what the intent is?

**Comment by 13r0ck** [comment]
I've also found `Animation.empty` to be a great placeholder when using animated `El`s to allow for the project to compile so I can see layout before I begin to animate.

**Comment by andrewMacmurray** [comment]
My thoughts on this are that I'd rather not include it unless it's requested by a number of people - I'd like to keep the api deliberately minimal and not add helpers that could be specific to people's use cases (this is a general philosophy followed by many of the core Elm libraries).

One thing I often do in these situations is define a module in a project for extras - e.g.:

```elm
module Utils.Animation exposing (empty)


empty : Animation
empty =
    Animation.fromTo
        { duration = 0
        , options = []
        }
        []
        []
```

And then use the same alias name in other modules so it "looks like" the same api:

```elm
import Simple.Animation as Animation
import Utils.Animation as Animation


myAnimation : Bool -> Animation
myAnimation shouldAnimate =
    if shouldAnimate then
        Animation.fromTo
            { duration = 500
            , options = []
            }
            [ P.x 0 ]
            [ P.x 100 ]

    else
        Animation.empty
```

**Comment by 13r0ck** [comment]
I totally understand where you are coming from. It makes sense that elm-**simple**-animation's API should be **simple**. I just don't think that having a "none" definition is a specific use case, even [Elm-UI has a none](https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/Element#none). I think that including it just helps reduce boilerplate, and from what I can tell they are doing [the same thing](https://github.com/mdgriffith/elm-ui/blob/7aa0e015499d4975a4dda02c2629ee21ec18eac3/src/Element.elm#L539).
Thank you for the code examples, I had never thought of using two imports with the same name like that before. I'm sure I will find places where that comes up again!

**Comment by z5h** [comment]
My plan is to use an API I've developed that will have knowledge, during `view` of items that may be transitioning OR in a completed transition state. Specifically, when it's time to render an animation it will look like this:

```Elm
case status of
    Timeline.Transitioning from to progress -> 
       -- we are transitioning from a value to another, and have already made some progress
       -- east to turn this into an animation with a negative delay as we are "in flight"
    Timeline.At color ->
        -- ok, we need to return an "animation" but we are actually at rest. 
        -- We can handle this "ungracefully" with the current API. 
        -- Will browsers like it or optimize it? I'm not sure.
```
