### ISSUE TITLE
More in depth mouse hover example

### ISSUE THREAD

**Issue by MartinSStewart** [andrewMacmurray/elm-simple-animation#17]
In the readme there's an example of a transition triggering on mouse hover
![image](https://user-images.githubusercontent.com/5068391/116859815-e3fe3f80-ac00-11eb-922b-110742419099.png)
It's not clear to me though where the `"gold-box-on-hover"` class comes from. Maybe you could provide an ellie example of how this works?

**Comment by andrewMacmurray** [comment]
How about this? https://ellie-app.com/d54JpCBcbWLa1

**Comment by MartinSStewart** [comment]
Yes, that makes it much more clear. Thank you!

**Comment by andrewMacmurray** [comment]
@MartinSStewart would you mind checking these if you have a moment? Have added a few more for the other examples in the README. Cheers for the input, it's improving the quality nicely 👍 

https://github.com/andrewMacmurray/elm-simple-animation/pull/18

**Comment by andrewMacmurray** [comment]
closed with #18
