### ISSUE TITLE
Please add this to the wiki

### ISSUE THREAD

**Issue by rolojf** [andrewMacmurray/elm-simple-animation#21]
Andrew

This is very useful.  I suggest that you put it on the wiki, readme or something.
In slack is about to get lost.

Regards,
![commentInSlack](https://user-images.githubusercontent.com/24816104/120025465-51aa4b00-bfb6-11eb-8c49-1e3394c98c28.png)

**Comment by andrewMacmurray** [comment]
Thanks for this, I've referenced this in a discussion in #16, if you've got any thoughts on it would be great to hear them there!
